/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package io.github.kayr.ezyquery

import net.sf.jsqlparser.parser.CCJSqlParser
import net.sf.jsqlparser.parser.CCJSqlParserUtil
import net.sf.jsqlparser.parser.JSqlParser
import spock.lang.Specification

class LibraryTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
//        def t = CCJSqlParserUtil.parseExpression("true() && a > 8.5 and c = 'JJJJ' and (a = b or c = 9)")
//        def t = CCJSqlParserUtil.parseExpression("6 in (9,a = b)")
//        def t = CCJSqlParserUtil.parseExpression("8 <> 9")
//        def t = CCJSqlParserUtil.parseExpression("6 in 9")
        def t = CCJSqlParserUtil.parseExpression("6 is null")



        println(t)

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
