/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.kayr.ezyquery;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
